version: "3.9"

services:
  web:
    image: ammarymn/webserver
    build: ./webserver
    restart: always
    ports:
      - 80:80
    environment:
      FRONTEND_SERVER_NAME: frontend
      FRONTEND_SERVER_PORT: 3000
      BACKEND_SERVER_NAME: backend
      BACKEND_SERVER_PORT: 8080

    depends_on:
      - frontend
      - backend
      

  frontend:
    image: ammarymn/frontend
    build: ./frontend
    restart: always
    expose:
      - 3000
    
  backend:
    image: ammarymn/backend
    build: ./backend
    restart: always
    expose:
      - 8080